# Author: LKouadio <etanoyau@gmail.com>
# License: LGPL-3.0
r"""Native 1-D magnetotelluric forward modelling for Occam inversion.

The implementation evaluates the exact plane-wave response of an isotropic,
horizontally layered earth. It is independent of native Occam text formats
and provides the scientific foundation for Jacobian and inversion modules.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any

import numpy as np

from . import _numba_kernels
from .base import Occam1DBase
from .data import Occam1DData
from .model import Occam1DModel
from .schema import MODE_OPTIONS

__all__ = ["Occam1DForwardModel", "Occam1DForwardResponse"]

_MU0 = 4.0e-7 * math.pi
_RHO_CODE = 103
_PHASE_CODE = 104
_LOG10_MAX = math.log10(np.finfo(float).max)
_LOG10_MIN = math.log10(np.nextafter(0.0, 1.0))
_THICK_LAYER_LIMIT = 50.0


def _readonly(values, dtype) -> np.ndarray:
    """Return a detached, immutable one-dimensional NumPy array."""
    result = np.array(values, dtype=dtype, copy=True)
    if result.ndim != 1:
        raise ValueError("Forward-response arrays must be one-dimensional.")
    result.setflags(write=False)
    return result


def _stable_complex_tanh(values: np.ndarray) -> np.ndarray:
    r"""Evaluate tanh using its passive thick-layer asymptote.

    Propagation arguments generated by positive frequency, permeability,
    resistivity, and thickness have non-negative real parts. Once the real
    part exceeds 50, the difference between tanh and one is below ordinary
    double-precision relevance, while direct complex ``tanh`` may overflow
    internally through its exponential representation.
    """
    arguments = np.asarray(values, dtype=complex)
    thick = arguments.real >= _THICK_LAYER_LIMIT
    result = np.ones(arguments.shape, dtype=complex)
    if np.any(~thick):
        result[~thick] = np.tanh(arguments[~thick])
    return result


@dataclass(frozen=True)
class Occam1DForwardResponse:
    r"""Immutable physical response of one layered-earth calculation.

    Parameters
    ----------
    frequency : array-like of shape (n_frequencies,)
        Frequencies in hertz, retained in caller order.
    impedance : array-like of shape (n_frequencies,)
        Canonical scalar surface impedance in ohms. The canonical 1-D
        impedance has positive phase; tensor component signs are exposed by
        :meth:`Occam1DForwardModel.tensor_impedance`.
    resistivity : array-like of shape (n_frequencies,)
        Apparent resistivity in ohm metres.
    phase : array-like of shape (n_frequencies,)
        Component-convention phase in degrees.
    mode : {"xy", "yx", "te", "tm", "determinant"}
        Response convention used for phase normalization.
    metadata : mapping, optional
        Calculation provenance. A defensive, read-only copy is retained.

    Notes
    -----
    Arrays are detached and marked read-only. Missing values are not expected
    from a successful forward calculation; non-finite output is rejected.
    """

    frequency: np.ndarray
    impedance: np.ndarray
    resistivity: np.ndarray
    phase: np.ndarray
    mode: str
    metadata: Any = None

    def __post_init__(self) -> None:
        """Normalize immutable arrays and validate physical invariants."""
        frequency = _readonly(self.frequency, float)
        impedance = _readonly(self.impedance, complex)
        resistivity = _readonly(self.resistivity, float)
        phase = _readonly(self.phase, float)
        sizes = {
            frequency.size,
            impedance.size,
            resistivity.size,
            phase.size,
        }
        if len(sizes) != 1 or not frequency.size:
            raise ValueError(
                "Forward-response arrays must be non-empty and aligned."
            )
        if np.any(~np.isfinite(frequency)) or np.any(frequency <= 0):
            raise ValueError("frequency must be finite and strictly positive.")
        if np.any(~np.isfinite(impedance)):
            raise ValueError("impedance must contain only finite values.")
        if np.any(~np.isfinite(resistivity)) or np.any(resistivity <= 0):
            raise ValueError(
                "apparent resistivity must be finite and positive."
            )
        if np.any(~np.isfinite(phase)):
            raise ValueError("phase must contain only finite values.")
        mode = str(self.mode).strip().lower()
        if mode not in MODE_OPTIONS:
            choices = ", ".join(sorted(MODE_OPTIONS))
            raise ValueError(f"mode must be one of: {choices}.")
        metadata = {} if self.metadata is None else dict(self.metadata)
        object.__setattr__(self, "frequency", frequency)
        object.__setattr__(self, "impedance", impedance)
        object.__setattr__(self, "resistivity", resistivity)
        object.__setattr__(self, "phase", phase)
        object.__setattr__(self, "mode", mode)
        object.__setattr__(self, "metadata", MappingProxyType(metadata))

    @property
    def n_frequencies(self) -> int:
        """Number of calculated frequency samples."""
        return int(self.frequency.size)

    @property
    def period(self) -> np.ndarray:
        """Read-only periods in seconds, aligned with frequency."""
        result = np.reciprocal(self.frequency)
        result.setflags(write=False)
        return result

    @property
    def log10_resistivity(self) -> np.ndarray:
        """Read-only apparent resistivity in native log10 units."""
        result = np.log10(self.resistivity)
        result.setflags(write=False)
        return result

    def solver_values(self, type_code: int) -> np.ndarray:
        """Return values in native Occam solver units for one data type.

        Type 103 returns log10 apparent resistivity. Type 104 returns phase
        in degrees. Other codes raise because this solver does not silently
        invent a response convention.
        """
        if type_code == _RHO_CODE:
            return self.log10_resistivity
        if type_code == _PHASE_CODE:
            return self.phase
        raise ValueError("type_code must be 103 (resistivity) or 104 (phase).")

    def to_records(self) -> list[dict[str, float]]:
        """Return JSON-friendly physical response records."""
        return [
            {
                "frequency_hz": float(self.frequency[index]),
                "period_s": float(1.0 / self.frequency[index]),
                "impedance_real_ohm": float(self.impedance[index].real),
                "impedance_imag_ohm": float(self.impedance[index].imag),
                "resistivity_ohm_m": float(self.resistivity[index]),
                "phase_deg": float(self.phase[index]),
            }
            for index in range(self.n_frequencies)
        ]

    def diagnostics(self) -> dict[str, Any]:
        """Return JSON-safe response ranges and provenance."""
        return {
            "mode": self.mode,
            "n_frequencies": self.n_frequencies,
            "frequency_min_hz": float(np.min(self.frequency)),
            "frequency_max_hz": float(np.max(self.frequency)),
            "resistivity_min_ohm_m": float(np.min(self.resistivity)),
            "resistivity_max_ohm_m": float(np.max(self.resistivity)),
            "phase_min_deg": float(np.min(self.phase)),
            "phase_max_deg": float(np.max(self.phase)),
            "metadata": dict(self.metadata),
        }


class Occam1DForwardModel(Occam1DBase):
    r"""Evaluate isotropic 1-D MT responses for an Occam layer geometry.

    Parameters
    ----------
    model : Occam1DModel, optional
        Bound layer geometry and default physical resistivities. A defensive
        geometry copy is retained. A model may instead be passed to
        :meth:`predict`.
    permeability : float, default=4*pi*1e-7
        Uniform magnetic permeability in henries per metre. The default is
        vacuum permeability. Magnetic permeability contrasts are outside the
        current isotropic Occam1D parameterization.
    verbose, logger, metadata, stream
        Shared :class:`Occam1DBase` options.

    Notes
    -----
    For angular frequency :math:`\omega`, layer resistivity :math:`\rho_j`,
    and thickness :math:`h_j`, define

    .. math::

       \gamma_j=\sqrt{i\omega\mu/\rho_j},\qquad
       \eta_j=\sqrt{i\omega\mu\rho_j}.

    Beginning with basement impedance :math:`Z_N=\eta_N`, the recursion is

    .. math::

       Z_j=\eta_j\frac{Z_{j+1}+\eta_j\tanh(\gamma_jh_j)}
       {\eta_j+Z_{j+1}\tanh(\gamma_jh_j)}.

    Apparent resistivity is :math:`|Z|^2/(\mu\omega)`. The branch used by
    NumPy gives the expected 45-degree uniform-half-space phase.

    Examples
    --------
    >>> model = Occam1DModel([0.0, 100.0], [100.0, 100.0])
    >>> forward = Occam1DForwardModel(model)
    >>> response = forward.predict([1.0, 10.0])
    >>> response.resistivity.tolist()
    [100.0, 100.0]
    >>> response.phase.tolist()
    [45.0, 45.0]
    """

    def __init__(self, model=None, *, permeability=_MU0, **kwargs):
        super().__init__(**kwargs)
        self.permeability = self._positive_scalar(
            "permeability", permeability
        )
        self._depth: np.ndarray | None = None
        self._default_resistivity: np.ndarray | None = None
        if model is not None:
            self.bind_model(model)

    @staticmethod
    def _positive_scalar(name: str, value) -> float:
        """Return a finite strictly positive real scalar."""
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise TypeError(f"{name} must be a real number.")
        result = float(value)
        if not math.isfinite(result) or result <= 0:
            raise ValueError(f"{name} must be finite and strictly positive.")
        return result

    @staticmethod
    def _frequency(values) -> np.ndarray:
        """Return a finite, positive, non-empty frequency vector."""
        try:
            result = np.array(values, dtype=float, copy=True)
        except (TypeError, ValueError) as error:
            raise TypeError("frequency must contain real numbers.") from error
        if result.ndim != 1 or not result.size:
            raise ValueError(
                "frequency must be a non-empty one-dimensional vector."
            )
        if np.any(~np.isfinite(result)) or np.any(result <= 0):
            raise ValueError("frequency must be finite and strictly positive.")
        return result

    @staticmethod
    def _mode(value) -> str:
        """Return one canonical supported component mode."""
        if not isinstance(value, str):
            raise TypeError("mode must be a string.")
        mode = value.strip().lower()
        if mode not in MODE_OPTIONS:
            choices = ", ".join(sorted(MODE_OPTIONS))
            raise ValueError(f"mode must be one of: {choices}.")
        return mode

    def bind_model(self, model: Occam1DModel):
        """Bind a defensive copy of validated layer geometry and values.

        Returns
        -------
        Occam1DForwardModel
            ``self`` for fluent workflow construction.
        """
        if not isinstance(model, Occam1DModel):
            raise TypeError("model must be an Occam1DModel instance.")
        model.validate()
        self._depth = np.array(model.depth, dtype=float, copy=True)
        self._default_resistivity = np.array(
            model.resistivity,
            dtype=float,
            copy=True,
        )
        self.update_metadata(n_layers=model.n_layers)
        return self

    @property
    def is_configured(self) -> bool:
        """Whether a layer geometry has been bound."""
        return self._depth is not None

    @property
    def n_layers(self) -> int:
        """Number of bound layers, including the half-space."""
        return 0 if self._depth is None else int(self._depth.size)

    @property
    def depth(self) -> np.ndarray | None:
        """Independent copy of bound layer-top depths in metres."""
        return None if self._depth is None else self._depth.copy()

    @property
    def thickness(self) -> np.ndarray | None:
        """Finite-layer thicknesses in metres, excluding the half-space."""
        return None if self._depth is None else np.diff(self._depth)

    def _resolve_model(
        self,
        model,
        resistivity,
        log10_resistivity,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Resolve one geometry and exactly one parameter representation."""
        if resistivity is not None and log10_resistivity is not None:
            raise ValueError(
                "Provide resistivity or log10_resistivity, not both."
            )
        if model is not None:
            if not isinstance(model, Occam1DModel):
                raise TypeError("model must be an Occam1DModel instance.")
            model.validate()
            depth = np.array(model.depth, dtype=float, copy=True)
            default = np.array(model.resistivity, dtype=float, copy=True)
        else:
            if self._depth is None or self._default_resistivity is None:
                raise RuntimeError(
                    "No layer model is available. Bind one or pass model."
                )
            depth = self._depth.copy()
            default = self._default_resistivity.copy()
        if log10_resistivity is not None:
            values = self._parameter_vector(
                log10_resistivity,
                depth.size,
                "log10_resistivity",
            )
            if np.any(values > _LOG10_MAX) or np.any(values < _LOG10_MIN):
                raise ValueError(
                    "log10_resistivity exceeds representable physical range."
                )
            with np.errstate(over="raise", under="ignore", invalid="raise"):
                rho = np.power(10.0, values)
        elif resistivity is not None:
            rho = self._parameter_vector(
                resistivity,
                depth.size,
                "resistivity",
            )
        else:
            rho = default
        if np.any(~np.isfinite(rho)) or np.any(rho <= 0):
            raise ValueError(
                "Every forward-model resistivity must be finite and positive."
            )
        return depth, rho

    @staticmethod
    def _parameter_vector(values, size: int, name: str) -> np.ndarray:
        """Return a finite one-dimensional layer parameter vector."""
        try:
            result = np.array(values, dtype=float, copy=True)
        except (TypeError, ValueError) as error:
            raise TypeError(f"{name} must contain real numbers.") from error
        if result.ndim != 1 or result.size != size:
            raise ValueError(f"{name} must have shape ({size},).")
        if np.any(~np.isfinite(result)):
            raise ValueError(f"{name} must contain only finite values.")
        return result

    def impedance(
        self,
        frequency,
        *,
        model=None,
        resistivity=None,
        log10_resistivity=None,
    ) -> np.ndarray:
        r"""Calculate canonical scalar surface impedance in ohms.

        Parameters
        ----------
        frequency : array-like of shape (n_frequencies,)
            Positive frequencies in hertz. Caller order is preserved.
        model : Occam1DModel, optional
            Per-call geometry and default resistivity override.
        resistivity : array-like of shape (n_layers,), optional
            Physical layer resistivities in ohm metres.
        log10_resistivity : array-like of shape (n_layers,), optional
            Base-10 logarithm of physical layer resistivity.

        Returns
        -------
        ndarray of complex, shape (n_frequencies,)
            Canonical positive-phase surface impedance in ohms.
        """
        frequencies = self._frequency(frequency)
        depth, rho = self._resolve_model(
            model,
            resistivity,
            log10_resistivity,
        )
        thickness = np.diff(depth)
        omega = 2.0 * math.pi * frequencies
        if _numba_kernels.HAS_NUMBA:
            impedance = self._recurse_numba(frequencies, rho, thickness, omega)
        else:
            impedance = self._recurse_numpy(frequencies, rho, thickness, omega)
        if np.any(~np.isfinite(impedance)):
            raise FloatingPointError(
                "Layered-earth recursion produced non-finite impedance."
            )
        return impedance

    def _recurse_numba(self, frequencies, rho, thickness, omega) -> np.ndarray:
        """Evaluate the layer recursion with the compiled kernel."""
        impedance, bad_frequency, bad_layer = _numba_kernels.impedance_kernel(
            rho,
            thickness,
            omega,
            self.permeability,
            _THICK_LAYER_LIMIT,
        )
        if bad_frequency >= 0:
            raise FloatingPointError(
                "Layer recursion became singular at layer "
                f"{bad_layer + 1}, frequency {frequencies[bad_frequency]:g} Hz."
            )
        return impedance

    def _recurse_numpy(self, frequencies, rho, thickness, omega) -> np.ndarray:
        """Evaluate the layer recursion vectorized over frequency."""
        imaginary_omega_mu = 1j * omega * self.permeability
        impedance = np.sqrt(imaginary_omega_mu * rho[-1])
        for index in range(rho.size - 2, -1, -1):
            intrinsic = np.sqrt(imaginary_omega_mu * rho[index])
            propagation = np.sqrt(
                imaginary_omega_mu / rho[index]
            )
            transfer = _stable_complex_tanh(
                propagation * thickness[index]
            )
            numerator = impedance + intrinsic * transfer
            denominator = intrinsic + impedance * transfer
            scale = np.maximum(
                np.abs(intrinsic),
                np.abs(impedance * transfer),
            )
            tolerance = np.finfo(float).eps * np.maximum(
                scale,
                np.finfo(float).tiny,
            )
            if np.any(np.abs(denominator) <= tolerance):
                bad = int(np.flatnonzero(np.abs(denominator) <= tolerance)[0])
                raise FloatingPointError(
                    "Layer recursion became singular at layer "
                    f"{index + 1}, frequency {frequencies[bad]:g} Hz."
                )
            impedance = intrinsic * numerator / denominator
        return impedance

    def tensor_impedance(self, frequency, **kwargs) -> np.ndarray:
        r"""Return the isotropic antisymmetric impedance tensor.

        The output has shape ``(n_frequencies, 2, 2)`` with
        :math:`Z_{xy}=Z` and :math:`Z_{yx}=-Z`; diagonal elements are zero.
        """
        scalar = self.impedance(frequency, **kwargs)
        tensor = np.zeros((scalar.size, 2, 2), dtype=complex)
        tensor[:, 0, 1] = scalar
        tensor[:, 1, 0] = -scalar
        return tensor

    def predict(
        self,
        frequency,
        *,
        model=None,
        resistivity=None,
        log10_resistivity=None,
        mode="determinant",
    ) -> Occam1DForwardResponse:
        """Return physical apparent resistivity and phase predictions."""
        frequencies = self._frequency(frequency)
        selected_mode = self._mode(mode)
        depth, rho = self._resolve_model(
            model,
            resistivity,
            log10_resistivity,
        )
        impedance = self.impedance(
            frequencies,
            model=Occam1DModel(depth, rho),
        )
        omega = 2.0 * math.pi * frequencies
        apparent = np.abs(impedance) ** 2 / (
            self.permeability * omega
        )
        phase = np.degrees(np.angle(impedance))
        if selected_mode in {"yx", "tm"}:
            phase = np.mod(np.degrees(np.angle(-impedance)), 180.0)
        if np.any(~np.isfinite(apparent)) or np.any(apparent <= 0):
            raise FloatingPointError(
                "Forward calculation produced invalid apparent resistivity."
            )
        return Occam1DForwardResponse(
            frequency=frequencies,
            impedance=impedance,
            resistivity=apparent,
            phase=phase,
            mode=selected_mode,
            metadata={
                "n_layers": int(depth.size),
                "permeability_h_per_m": self.permeability,
                "parameterization": "log10_resistivity",
                "earth": "isotropic_1d",
            },
        )

    def predict_data(
        self,
        data: Occam1DData,
        *,
        model=None,
        resistivity=None,
        log10_resistivity=None,
    ) -> Occam1DForwardResponse:
        """Predict a response using an :class:`Occam1DData` grid and mode."""
        if not isinstance(data, Occam1DData):
            raise TypeError("data must be an Occam1DData instance.")
        data.validate()
        return self.predict(
            data.frequency,
            model=model,
            resistivity=resistivity,
            log10_resistivity=log10_resistivity,
            mode=data.mode,
        )

    def solver_vector(
        self,
        data: Occam1DData,
        *,
        model=None,
        resistivity=None,
        log10_resistivity=None,
    ) -> np.ndarray:
        """Return predictions aligned with native observed-data row order.

        For each frequency, a log10 apparent-resistivity prediction is added
        when the sounding has a finite resistivity observation, followed by a
        phase prediction when it has a finite phase observation. The result
        therefore has shape ``(data.n_data,)``.
        """
        response = self.predict_data(
            data,
            model=model,
            resistivity=resistivity,
            log10_resistivity=log10_resistivity,
        )
        values = []
        log_rho = response.log10_resistivity
        resistivity_mask = data.resistivity_mask
        phase_mask = data.phase_mask
        for index in range(data.n_frequencies):
            if resistivity_mask[index]:
                values.append(log_rho[index])
            if phase_mask[index]:
                values.append(response.phase[index])
        result = np.asarray(values, dtype=float)
        if result.shape != (data.n_data,):
            raise RuntimeError(
                "Internal response alignment failed for Occam1D data."
            )
        return result

    def diagnostics(self) -> dict[str, Any]:
        """Extend lifecycle diagnostics with forward-model configuration."""
        values = super().diagnostics()
        values.update(
            {
                "is_configured": self.is_configured,
                "n_layers": self.n_layers,
                "permeability_h_per_m": self.permeability,
                "formulation": "isotropic_layered_mt",
            }
        )
        return values
