"""Reusable configuration template I/O for inversion models."""

from __future__ import annotations

import ast
import json
from dataclasses import asdict, dataclass, fields, is_dataclass
from pathlib import Path
from textwrap import wrap
from typing import Any

PathLike = str | Path

__all__ = [
    "ConfigParameter",
    "read_config_file",
    "write_config_template",
]


@dataclass(frozen=True)
class ConfigParameter:
    """Description of one editable configuration parameter.

    Parameters
    ----------
    name : str
        Dataclass field name exposed in the generated
        configuration file.
    description : str
        Human-readable explanation written as comments in
        Python and YAML templates, and as metadata in JSON
        templates.
    group : str, default "General"
        Section heading used to organize long configuration
        files into related parameter groups.
    """

    name: str
    description: str
    group: str = "General"


def _config_dict(config: Any) -> dict[str, Any]:
    """Return a plain dictionary from a dataclass or mapping."""
    if is_dataclass(config):
        return asdict(config)
    return dict(config)


def _field_names(config_cls: type[Any]) -> set[str]:
    """Return dataclass field names for ``config_cls``."""
    if not is_dataclass(config_cls):
        msg = "config_cls must be a dataclass type."
        raise TypeError(msg)
    return {f.name for f in fields(config_cls)}


def _format_name(path: PathLike, fmt: str | None) -> str:
    """Normalize a requested configuration format."""
    if fmt is None:
        suffix = Path(path).suffix.lower()
        if suffix in {".json", ".yml", ".yaml"}:
            return suffix.lstrip(".")
        return "py"
    fmt = fmt.lower().lstrip(".")
    if fmt == "yaml":
        return "yml"
    if fmt not in {"py", "json", "yml"}:
        msg = "fmt must be one of 'py', 'json', 'yml', or 'yaml'."
        raise ValueError(msg)
    return fmt


def _target_path(path: PathLike, fmt: str) -> Path:
    """Return ``path`` with a configuration suffix if missing."""
    p = Path(path)
    if p.suffix:
        return p
    suffix = ".yml" if fmt == "yml" else f".{fmt}"
    return p.with_suffix(suffix)


def _schema_map(
    schema: list[ConfigParameter],
) -> dict[str, ConfigParameter]:
    """Return schema entries keyed by parameter name."""
    return {entry.name: entry for entry in schema}


def _groups(
    values: dict[str, Any],
    schema: list[ConfigParameter],
) -> list[tuple[str, list[str]]]:
    """Group parameter names while preserving dataclass order."""
    by_name = _schema_map(schema)
    grouped: dict[str, list[str]] = {}
    order: list[str] = []
    for name in values:
        group = by_name.get(name, ConfigParameter(name, "")).group
        if group not in grouped:
            grouped[group] = []
            order.append(group)
        grouped[group].append(name)
    return [(group, grouped[group]) for group in order]


def _comment_lines(text: str, prefix: str) -> list[str]:
    """Wrap ``text`` into comment lines."""
    clean = " ".join(text.split())
    if not clean:
        return []
    width = max(20, 70 - len(prefix))
    return [f"{prefix}{line}" for line in wrap(clean, width=width)]


def _py_value(value: Any) -> str:
    """Return a stable Python literal for a template value."""
    return repr(value)


def _yaml_value(value: Any) -> str:
    """Return a small YAML scalar representation."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    return json.dumps(value)


def _write_python(
    path: Path,
    values: dict[str, Any],
    schema: list[ConfigParameter],
    title: str,
) -> None:
    """Write a commented Python configuration template."""
    by_name = _schema_map(schema)
    lines = [
        '"""Source-of-truth configuration generated by PyCSAMT."""',
        "",
        f"# {title}",
        "# Edit values in CONFIG, then load with from_file().",
        "# Keep this file as the reproducible record of the run.",
        "",
        "CONFIG = {",
    ]
    for group, names in _groups(values, schema):
        lines.append(f"    # ---- {group} ----")
        for name in names:
            entry = by_name.get(name)
            if entry is not None:
                comments = _comment_lines(entry.description, "    # ")
                for comment in comments:
                    lines.append(comment)
            lines.append(f"    {name!r}: {_py_value(values[name])},")
            lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    path.write_text("\n".join(lines) + "\n")


def _write_json(
    path: Path,
    values: dict[str, Any],
    schema: list[ConfigParameter],
    title: str,
) -> None:
    """Write a JSON configuration with embedded metadata."""
    by_name = _schema_map(schema)
    payload: dict[str, Any] = {
        "_schema": {
            "title": title,
            "note": (
                "Edit values under 'config'. The '_schema' block "
                "is documentation and is ignored by from_file()."
            ),
            "parameters": {
                name: {
                    "group": by_name.get(name).group
                    if name in by_name
                    else "General",
                    "description": by_name.get(name).description
                    if name in by_name
                    else "",
                }
                for name in values
            },
        },
        "config": values,
    }
    text = json.dumps(payload, indent=2, sort_keys=False)
    path.write_text(text + "\n")


def _write_yaml(
    path: Path,
    values: dict[str, Any],
    schema: list[ConfigParameter],
    title: str,
) -> None:
    """Write a commented YAML configuration template."""
    by_name = _schema_map(schema)
    lines = [
        f"# {title}",
        "# Edit values, then load with from_file().",
        "# Comments are ignored by the YAML reader.",
        "",
    ]
    for group, names in _groups(values, schema):
        lines.append(f"# ---- {group} ----")
        for name in names:
            entry = by_name.get(name)
            if entry is not None:
                lines.extend(_comment_lines(entry.description, "# "))
            lines.append(f"{name}: {_yaml_value(values[name])}")
            lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n")


def write_config_template(
    path: PathLike,
    config: Any,
    schema: list[ConfigParameter],
    *,
    fmt: str | None = None,
    title: str = "PyCSAMT model configuration",
) -> Path:
    """Write an editable source-of-truth configuration file.

    Parameters
    ----------
    path : path-like
        Destination path. If the path has no suffix, one is
        added from ``fmt``. The default format is Python.
    config : dataclass or mapping
        Configuration values written to the template.
    schema : list of ConfigParameter
        Parameter documentation used to write comments and
        metadata.
    fmt : {"py", "json", "yml", "yaml"}, optional
        Output format. If omitted, the suffix of ``path`` is
        used. Paths without a suffix default to ``"py"``.
    title : str, default "PyCSAMT model configuration"
        Human-readable title written near the top of the file.

    Returns
    -------
    pathlib.Path
        Path of the generated configuration file.
    """
    out_fmt = _format_name(path, fmt)
    out = _target_path(path, out_fmt)
    out.parent.mkdir(parents=True, exist_ok=True)
    values = _config_dict(config)
    if out_fmt == "py":
        _write_python(out, values, schema, title)
    elif out_fmt == "json":
        _write_json(out, values, schema, title)
    else:
        _write_yaml(out, values, schema, title)
    return out


def _read_python(path: Path) -> dict[str, Any]:
    """Read a Python template containing ``CONFIG``."""
    tree = ast.parse(path.read_text())
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                is_config = (
                    isinstance(target, ast.Name)
                    and target.id == "CONFIG"
                )
                if is_config:
                    data = ast.literal_eval(node.value)
                    if isinstance(data, dict):
                        return data
        if isinstance(node, ast.AnnAssign):
            target = node.target
            is_config = (
                isinstance(target, ast.Name)
                and target.id == "CONFIG"
            )
            if is_config:
                data = ast.literal_eval(node.value)
                if isinstance(data, dict):
                    return data
    msg = f"Python config {path!s} must define a CONFIG dictionary."
    raise ValueError(msg)


def _read_yaml(path: Path) -> dict[str, Any]:
    """Read a YAML mapping using PyYAML when available."""
    try:
        import yaml
    except ImportError as exc:
        msg = "Reading YAML configuration files requires PyYAML."
        raise ImportError(msg) from exc
    data = yaml.safe_load(path.read_text())
    if data is None:
        return {}
    if not isinstance(data, dict):
        msg = f"YAML config {path!s} must contain a mapping."
        raise ValueError(msg)
    return data


def _read_json(path: Path) -> dict[str, Any]:
    """Read a JSON configuration mapping."""
    data = json.loads(path.read_text())
    if not isinstance(data, dict):
        msg = f"JSON config {path!s} must contain an object."
        raise ValueError(msg)
    if "config" in data and isinstance(data["config"], dict):
        return data["config"]
    return data


def read_config_file(
    path: PathLike,
    config_cls: type[Any],
    *,
    strict: bool = True,
) -> dict[str, Any]:
    """Read a generated configuration file into keyword values.

    Parameters
    ----------
    path : path-like
        Python, JSON, YAML, or YML configuration file.
    config_cls : type
        Dataclass type used to decide which keys are allowed.
    strict : bool, default True
        If ``True``, unknown keys raise :class:`ValueError`.
        If ``False``, unknown keys and metadata keys beginning
        with ``"_"`` are ignored.

    Returns
    -------
    dict
        Keyword arguments suitable for constructing
        ``config_cls``.
    """
    p = Path(path)
    suffix = p.suffix.lower()
    if suffix == ".py":
        data = _read_python(p)
    elif suffix == ".json":
        data = _read_json(p)
    elif suffix in {".yml", ".yaml"}:
        data = _read_yaml(p)
    else:
        msg = (
            "Unsupported config suffix. Use .py, .json, "
            ".yml, or .yaml."
        )
        raise ValueError(msg)

    allowed = _field_names(config_cls)
    values = {k: v for k, v in data.items() if not k.startswith("_")}
    unknown = sorted(set(values) - allowed)
    if unknown and strict:
        msg = "Unknown configuration parameter(s): "
        raise ValueError(msg + ", ".join(unknown))
    return {k: v for k, v in values.items() if k in allowed}
