#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Code benchmark case 021
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""
from __future__ import annotations

import numpy as np
import matplotlib.pyplot as plt

import os
os.makedirs('D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_021\\outputs', exist_ok=True)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites
sites = ensure_sites('D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset', verbose=0)
print(f"Loaded {len(list(sites))} stations")

sites_corr = sites  # no static-shift correction

plt.show()
print("Workflow complete.")
