#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Code benchmark case 010
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""
from __future__ import annotations

import numpy as np
import matplotlib.pyplot as plt

import os
os.makedirs('D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_010\\outputs', exist_ok=True)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites
sites = ensure_sites('D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset', verbose=0)
print(f"Loaded {len(list(sites))} stations")

# ── static-shift correction ───────────────────────────────────
from pycsamt.emtools.ss import (
    estimate_ss_ama,
    correct_ss_ama,
    plot_ss_summary,
    plot_ss_1d_curves,
)
from pycsamt.emtools._core import (
    _get_z_block, _name, _iter_items,
)

ss_table = estimate_ss_ama(
    sites,
    half_window=3,
    sort_by="lon",
    weights="tri",
    max_skew=6.0,
)
print(
    ss_table[
        ["station", "delta_log10_rho", "fac_z"]
    ]
)

sites_corr = correct_ss_ama(
    sites,
    half_window=3,
    sort_by="lon",
)


def _collect_logRho(S):
    rows, freqs = [], None
    for i, ed in enumerate(_iter_items(S)):
        Z, z, fr = _get_z_block(ed)
        if Z is None:
            continue
        rxy = (
            0.2 * np.abs(z[:, 0, 1]) ** 2
            / (fr + 1e-24)
        )
        ryx = (
            0.2 * np.abs(z[:, 1, 0]) ** 2
            / (fr + 1e-24)
        )
        rows.append(
            np.log10(np.sqrt(rxy * ryx) + 1e-24)
        )
        freqs = fr
    return np.array(rows), freqs


logRho_b, ss_freqs = _collect_logRho(sites)
logRho_a, _ = _collect_logRho(sites_corr)
ss_labels = [
    _name(ed, i)
    for i, ed in enumerate(_iter_items(sites))
]

fig_sum = plot_ss_summary(
    logRho_b, logRho_a,
    freqs=ss_freqs,
    station_labels=ss_labels,
)
fig_sum.savefig(
    'D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_010\\outputs' + "/ss_summary.png",
    dpi=150, bbox_inches="tight",
)

fig_1d = plot_ss_1d_curves(
    logRho_b, logRho_a,
    freqs=ss_freqs,
    station_labels=ss_labels,
)
fig_1d.savefig(
    'D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_010\\outputs' + "/ss_1d_curves.png",
    dpi=150, bbox_inches="tight",
)

plt.show()
print("Workflow complete.")
