#!/usr/bin/env python
"""
Code benchmark case 014
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""

from __future__ import annotations

import os

import matplotlib.pyplot as plt

os.makedirs(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_014\\outputs",
    exist_ok=True,
)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites

sites = ensure_sites(
    "D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset",
    verbose=0,
)
print(f"Loaded {len(list(sites))} stations")

sites_corr = sites  # no static-shift correction

# ── phase tensor analysis ─────────────────────────────────────
from pycsamt.emtools.dimensionality import classify_dimensionality
from pycsamt.emtools.strike import (
    estimate_strike_consensus,
    plot_strike_analysis,
)
from pycsamt.emtools.tensor import (
    build_phase_tensor_table,
    plot_phase_tensor_psection,
)

pt_table = build_phase_tensor_table(sites_corr)
dim_table = classify_dimensionality(
    sites_corr,
    skew_th=5.0,
    ellipt_th=0.1,
)
st_result = estimate_strike_consensus(sites_corr)
strike_angle = st_result.get("angle_deg")
try:
    strike_text = f"{float(strike_angle):.1f} deg"
except (TypeError, ValueError):
    strike_text = "n/a"
print(f"Consensus strike: {strike_text}")

fig_pt = plot_phase_tensor_psection(sites_corr).get_figure()
fig_pt.savefig(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_014\\outputs"
    + "/pt_psection.png",
    dpi=150,
    bbox_inches="tight",
)
fig_strike = plot_strike_analysis(sites_corr)
fig_strike.savefig(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_014\\outputs"
    + "/strike_analysis.png",
    dpi=150,
    bbox_inches="tight",
)

plt.show()
print("Workflow complete.")
