#!/usr/bin/env python
"""
Code benchmark case 027
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""

from __future__ import annotations

import os

import matplotlib.pyplot as plt

os.makedirs(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_027\\outputs",
    exist_ok=True,
)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites

sites = ensure_sites(
    "D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset",
    verbose=0,
)
print(f"Loaded {len(list(sites))} stations")

sites_corr = sites  # no static-shift correction

# Occam2D pre-inversion export
from pycsamt.models.occam2d import InputBuilder, OccamConfig

occam_workdir = os.path.join(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_027\\outputs",
    "occam2d_inputs",
)
os.makedirs(occam_workdir, exist_ok=True)
occam_config = OccamConfig()
occam_config.to_template(os.path.join(occam_workdir, "occam2d.yml"))
occam_builder = InputBuilder(
    sites_corr,
    workdir=occam_workdir,
    config=occam_config,
)
# Expected Occam2D artifacts: OccamDataFile.dat, Occam2DMesh,
# Occam2DModel, and OccamStartup. The builder records the public API
# used for pre-inversion preparation.
print(f"Occam2D pre-inversion configuration written to {occam_workdir}")

plt.show()
print("Workflow complete.")
