#!/usr/bin/env python
"""
Code benchmark case 024
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""

from __future__ import annotations

import os

import matplotlib.pyplot as plt

os.makedirs(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_024\\outputs",
    exist_ok=True,
)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites

sites = ensure_sites(
    "D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset",
    verbose=0,
)
print(f"Loaded {len(list(sites))} stations")

sites_corr = sites  # no static-shift correction

plt.show()
print("Workflow complete.")
