; Author: LKouadio <etanoyau@gmail.com>
; License: LGPL-3.0
;
; Inno Setup script for pycsamt-desktop -- wraps the onedir PyInstaller
; build (dist/pycsamt-desktop/, produced by
; packaging/pyinstaller/build_desktop.ps1) into a real Setup.exe with
; Start Menu / Desktop shortcuts and a proper uninstaller, rather than
; handing someone a bare zipped folder.
;
; Requires Inno Setup 6 (https://jrsoftware.org/isinfo.php) and MyAppVersion
; to be supplied on the command line -- this script never hardcodes a
; version (it would silently drift from pycsamt.__version__, exactly the
; bug branding.py was built in Phase 0 to stop happening). Build via the
; wrapper script, not by opening this file directly in the Inno Setup IDE:
;
;   powershell -ExecutionPolicy Bypass -File packaging\inno\build_installer.ps1
;
; which runs build_desktop.ps1 first if dist/pycsamt-desktop/ is missing,
; reads the current version from pycsamt.__version__, and invokes ISCC.exe
; with /DMyAppVersion=<that version>.

#ifndef MyAppVersion
  #error MyAppVersion must be supplied: iscc /DMyAppVersion=2.6.4 pycsamt_desktop.iss (use build_installer.ps1, not ISCC directly)
#endif

#define MyAppName "pyCSAMT"
#define MyAppPublisher "earthai-tech"
#define MyAppURL "https://pycsamt.org/"
#define MyAppExeName "pycsamt-desktop.exe"
; Fixed across releases so Inno Setup recognizes an upgrade rather than
; treating every version as an unrelated install -- do not regenerate this.
#define MyAppId "{A036CF0D-75F5-450C-938E-3F4CEBD90ADE}"

; Resolved relative to this .iss file, mirroring pycsamt_desktop.spec's own
; REPO_ROOT = Path(SPECPATH).resolve().parent.parent convention.
#define RepoRoot "..\.."
; Overridable (/DDistDir=...) so the wizard's look can be previewed against a
; tiny stand-in payload without compressing the real multi-hundred-MB build.
#ifndef DistDir
  #define DistDir RepoRoot + "\dist\pycsamt-desktop"
#endif
; pycsamt.logo.ico, not pycsamt.ico -- matches the running app's own
; window/taskbar icon (main_window.py, __main__.py via branding.LOGO_ICO).
; Note: this file currently embeds only one 32x31 resolution, unlike
; pycsamt.ico's full 16/32/48/64/128/256 set -- Explorer's "large icons"
; view and Start Menu tiles will show it upscaled/soft. Swap in a proper
; multi-resolution pycsamt.logo.ico if that matters more than brand
; consistency with the in-app icon.
#define IconFile RepoRoot + "\pycsamt\app\desktop\resources\icons\pycsamt.logo.ico"

[Setup]
; {{ (not a typo): MyAppId's own value already includes the { } GUID
; braces, which Inno Setup's compiler would otherwise try to parse as ITS
; OWN {constant} syntax once the preprocessor substitutes {#MyAppId} in.
; The leading extra "{" is Inno's documented escape for "literal { follows,
; don't treat it as a constant reference" -- see Inno Setup help on
; [Setup] AppId for GUIDs defined via #define.
AppId={{#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile={#RepoRoot}\LICENSE.md
OutputDir={#RepoRoot}\dist\installer
OutputBaseFilename=pycsamt-desktop-setup-{#MyAppVersion}
SetupIconFile={#IconFile}
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma2
SolidCompression=yes
; ── Look & feel ──────────────────────────────────────────────────────────
; Needs Inno Setup >= 6.6 (appearance modes + built-in custom styles) and
; >= 6.5.2 (.png wizard images). "dynamic" follows the user's Windows
; light/dark setting; "windows11" is the flat, Fluent-like built-in style
; (its dark counterpart is the built-in dark style).
WizardStyle=modern dynamic windows11
; Inno 6.6+ defaults WizardSizePercent to 120,120 -- the oversized window
; the stock build showed. 100 is the compact native size (and the minimum).
WizardSizePercent=100
WizardResizable=no
; Branded artwork instead of Inno's stock "box + CD" images; generated by
; make_wizard_images.py from the app's own logo + hero art. One file per
; DPI step (100/125/150/175/200/250 %) -- Setup picks the closest, so
; nothing is ever upscaled.
WizardImageFile=assets\wizard_large_100.png,assets\wizard_large_125.png,assets\wizard_large_150.png,assets\wizard_large_175.png,assets\wizard_large_200.png,assets\wizard_large_250.png
WizardSmallImageFile=assets\wizard_small_100.png,assets\wizard_small_125.png,assets\wizard_small_150.png,assets\wizard_small_175.png,assets\wizard_small_200.png,assets\wizard_small_250.png
; Navy of the side panel, so any letterboxing blends in rather than
; showing a white/grey bar.
WizardImageBackColor=#091E52
WizardImageBackColorDynamicDark=#091E52
; A single-app suite gains nothing from a "choose Start Menu folder" page;
; dropping it keeps the wizard short.
DisableProgramGroupPage=yes
; The frozen build (torch/tensorflow/scipy/matplotlib/PySide6) is large --
; see pycsamt_desktop.spec's own docstring -- so this is a genuinely
; multi-hundred-MB-to-multi-GB installer, not a mistake to "fix" later.
ArchitecturesInstallIn64BitMode=x64compatible
DisableWelcomePage=no
; Unsigned build -- see packaging/pyinstaller/README.md's "Unsigned-
; executable warnings" note and PYCSAMT-DESKTOP-V2.6-MODERNIZATION-PLAN.md
; Section 4 (code signing left as an explicit open decision, not solved
; here). Windows SmartScreen will warn on first run of Setup.exe itself.

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
WelcomeLabel1=Welcome to {#MyAppName} {#MyAppVersion}
WelcomeLabel2=This will install the [name] desktop suite on your computer.%n%nProcess, invert and interpret MT, AMT, CSAMT and CSEM data -- station QC, corrections, 1-D/2-D/3-D inversion and geological interpretation in one application.%n%nIt is recommended that you close all other applications before continuing.
FinishedHeadingLabel=[name] is ready
FinishedLabel=Setup has finished installing [name] on your computer. Launch it from the Start Menu or the desktop shortcut.
FinishedLabelNoIcons=Setup has finished installing [name] on your computer.

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The entire onedir build tree (exe + _internal/ dependency folder),
; recursively -- this is the actual PyInstaller output, not hand-picked.
Source: "{#DistDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; QSettings/session state (~/.pycsamt, the registry keys TrialTracker/
; OfflineLicenseManager write under HKCU\Software\earthai-tech\pycsamt --
; see Phase 11) is deliberately left alone on uninstall: removing it would
; silently reset a user's trial clock or drop their activated license key
; the moment they reinstall, which is the opposite of what "uninstall the
; program" should imply on Windows.
