#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Code benchmark case 038
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""
from __future__ import annotations

import numpy as np
import matplotlib.pyplot as plt

import os
os.makedirs('D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_038\\outputs', exist_ok=True)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites
sites = ensure_sites('D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset', verbose=0)
print(f"Loaded {len(list(sites))} stations")

sites_corr = sites  # no static-shift correction

# Tipper and induction-arrow analysis
from pycsamt.emtools.tf import (
    plot_induction_arrows,
    plot_tipper_hodograms,
    plot_tipper_polar,
)

try:
    ax_tip = plot_induction_arrows(
        sites_corr,
        periods=(1.0,),
        convention='park',
    )
    ax_tip.get_figure().savefig(
        'D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_038\\outputs' + "/induction_arrows.png",
        dpi=150, bbox_inches="tight",
    )
except Exception as exc:
    print(f"No plottable induction arrows: {exc}")

try:
    ax_hodo = plot_tipper_hodograms(sites_corr)
    ax_hodo.get_figure().savefig(
        'D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_038\\outputs' + "/tipper_hodograms.png",
        dpi=150, bbox_inches="tight",
    )
except Exception as exc:
    print(f"Tipper hodogram skipped: {exc}")

try:
    ax_polar = plot_tipper_polar(sites_corr, component='real')
    ax_polar.get_figure().savefig(
        'D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_038\\outputs' + "/tipper_polar.png",
        dpi=150, bbox_inches="tight",
    )
except Exception as exc:
    print(f"Tipper polar plot skipped: {exc}")

plt.show()
print("Workflow complete.")
