"""PCBH - pyCSAMT Common Borehole Format.

This package exposes the PCBH schema, JSON serialization, and deterministic
trajectory derivation. External-format adapters are introduced in later
phases.
"""

from .adapters import (
    from_legacy_borehole,
    legacy_borehole_views,
    legacy_conversion_losses,
    to_legacy_borehole,
)
from .benchmark import PCBHBenchmarkResult, benchmark_pcbh
from .builder import (
    BuilderDiagnostic,
    BuilderValidation,
    CSVMappingProfile,
    document_from_builder,
    document_to_builder,
    new_builder_draft,
    preview_csv_mapping,
    validate_builder,
)
from .csvio import (
    DEFAULT_CSV_MAX_BYTES,
    DEFAULT_CSV_MAX_ROWS,
    boreholes_from_csv,
)
from .exports import (
    ExportLoss,
    PCBHExportReport,
    write_geojson,
    write_gltf,
    write_vtp,
)
from .jsonio import (
    DEFAULT_MAX_BOREHOLES,
    DEFAULT_MAX_BYTES,
    DEFAULT_MAX_INTERVALS,
    DEFAULT_MAX_NESTING,
    PCBH_SCHEMA_URI,
    pcbh_from_dict,
    pcbh_to_dict,
    read_pcbh,
    write_pcbh,
)
from .lasio import LASExportReport, borehole_from_las, write_las_subset
from .mapping import (
    CANONICAL_CSV_FIELDS,
    REQUIRED_CSV_FIELDS,
    ImportIssue,
    ImportReport,
    PCBHCSVImportError,
)
from .pcsf import (
    AlignedTrajectoryPoint,
    BoreholeBoundsResult,
    PCBHAlignmentReport,
    PCBHAssociation,
    PCBHReference,
    align_pcbh_to_pcsf,
    embed_pcbh,
    extract_pcbh,
    pcbh_document_checksum,
    reference_pcbh,
)
from .relational import (
    RELATIONAL_VERSION,
    RelationalManifest,
    boreholes_from_csv_directory,
    write_csv_directory,
)
from .render import (
    BoreholeRenderBuilder,
    BoreholeRenderModel,
    CollarPrimitive,
    ContactPrimitive,
    DisplayRadiusPolicy,
    IntervalSegmentPrimitive,
    MaterialBatch,
    PCBHRenderModel,
    PolylinePrimitive,
    StructureGlyphPrimitive,
    build_render_model,
    deterministic_color,
)
from .schema import (
    AZIMUTH_DIRECTIONS,
    BOREHOLE_KINDS,
    BOREHOLE_STATUSES,
    DATA_NATURES,
    NORTH_REFERENCES,
    PCBH_VERSION,
    SEVERITIES,
    Collar,
    CoordinateReferenceSystem,
    LogInterval,
    PCBHBorehole,
    PCBHDocument,
    PCBHValidationError,
    StructureObservation,
    SurveyStation,
    Trajectory,
    UnitSystem,
    ValidationIssue,
    VocabularyEntry,
)
from .trajectory import (
    DesurveyedTrajectory,
    TrajectoryPoint,
    desurvey,
    trajectory_checksum,
)
from .xlsxio import (
    SheetOutline,
    WorkbookOutline,
    boreholes_from_xlsx,
    inspect_workbook,
)

__all__ = [
    "PCBH_VERSION",
    "PCBH_SCHEMA_URI",
    "PCBHBenchmarkResult",
    "benchmark_pcbh",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_MAX_BOREHOLES",
    "DEFAULT_MAX_INTERVALS",
    "DEFAULT_MAX_NESTING",
    "SEVERITIES",
    "BOREHOLE_KINDS",
    "BOREHOLE_STATUSES",
    "DATA_NATURES",
    "NORTH_REFERENCES",
    "AZIMUTH_DIRECTIONS",
    "ValidationIssue",
    "PCBHValidationError",
    "CoordinateReferenceSystem",
    "UnitSystem",
    "Collar",
    "VocabularyEntry",
    "SurveyStation",
    "Trajectory",
    "LogInterval",
    "StructureObservation",
    "PCBHBorehole",
    "PCBHDocument",
    "TrajectoryPoint",
    "DesurveyedTrajectory",
    "pcbh_to_dict",
    "pcbh_from_dict",
    "read_pcbh",
    "write_pcbh",
    "desurvey",
    "trajectory_checksum",
    "from_legacy_borehole",
    "to_legacy_borehole",
    "legacy_borehole_views",
    "legacy_conversion_losses",
    "DEFAULT_CSV_MAX_BYTES",
    "DEFAULT_CSV_MAX_ROWS",
    "SheetOutline",
    "WorkbookOutline",
    "inspect_workbook",
    "boreholes_from_xlsx",
    "CSVMappingProfile",
    "BuilderDiagnostic",
    "BuilderValidation",
    "new_builder_draft",
    "document_from_builder",
    "document_to_builder",
    "validate_builder",
    "preview_csv_mapping",
    "ExportLoss",
    "PCBHExportReport",
    "write_geojson",
    "write_vtp",
    "write_gltf",
    "CANONICAL_CSV_FIELDS",
    "REQUIRED_CSV_FIELDS",
    "ImportIssue",
    "ImportReport",
    "PCBHCSVImportError",
    "boreholes_from_csv",
    "RELATIONAL_VERSION",
    "RelationalManifest",
    "boreholes_from_csv_directory",
    "write_csv_directory",
    "LASExportReport",
    "borehole_from_las",
    "write_las_subset",
    "DisplayRadiusPolicy",
    "CollarPrimitive",
    "PolylinePrimitive",
    "IntervalSegmentPrimitive",
    "ContactPrimitive",
    "StructureGlyphPrimitive",
    "MaterialBatch",
    "BoreholeRenderModel",
    "PCBHRenderModel",
    "BoreholeRenderBuilder",
    "build_render_model",
    "deterministic_color",
    "PCBHReference",
    "PCBHAssociation",
    "AlignedTrajectoryPoint",
    "BoreholeBoundsResult",
    "PCBHAlignmentReport",
    "pcbh_document_checksum",
    "embed_pcbh",
    "reference_pcbh",
    "extract_pcbh",
    "align_pcbh_to_pcsf",
]
