#!/usr/bin/env python
"""
Code benchmark case 032
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""

from __future__ import annotations

import os

import matplotlib.pyplot as plt

os.makedirs(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_032\\outputs",
    exist_ok=True,
)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites

sites = ensure_sites(
    "D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset",
    verbose=0,
)
print(f"Loaded {len(list(sites))} stations")

sites_corr = sites  # no static-shift correction

# ── AI 1-D inversion ──────────────────────────────────────────
from pycsamt.ai.inversion import EMInverter1D
from pycsamt.forward.batch import generate_dataset

freqs_ai = [
    0.0001,
    0.000168,
    0.000283,
    0.000476,
    0.0008,
    0.001346,
    0.002264,
    0.003808,
    0.006404,
    0.010771,
    0.018116,
    0.03047,
    0.051248,
    0.086195,
    0.144974,
    0.243835,
    0.410113,
    0.689779,
    1.160155,
    1.951293,
    3.281928,
    5.519954,
    9.284145,
    15.61523,
    26.263635,
    44.173447,
    74.296395,
    124.960914,
    210.174801,
    353.498111,
    594.557071,
    1000.0,
]
n_layers = 5
n_samples = 32
epochs = 1

ds = generate_dataset(
    solver="mt1d",
    n_samples=n_samples,
    freqs=freqs_ai,
    n_layers=n_layers,
    noise_level=0.03,
    seed=42,
    n_jobs=1,
    verbose=False,
)
inv1d = EMInverter1D(
    arch="cnn1d",
    n_layers=n_layers,
    solver="mt1d",
)
inv1d.fit(ds.X, ds.y, epochs=epochs, batch_size=32, verbose=False)

obs_features = {
    f"synthetic_{i:02d}": feat
    for i, feat in enumerate(ds.X[: min(3, len(ds.X))])
}
predictions = {}
for site_name, feat in obs_features.items():
    pred = inv1d.predict(feat.reshape(1, -1))
    predictions[site_name] = pred[0]

print(f"AI 1-D inversion done: {len(predictions)} stations")

plt.show()
print("Workflow complete.")
