"""Format-neutral electromagnetic transfer-function scientific core."""

from .converters import (
    DataLossWarning,
    EMTFEDIConversionError,
    SpectraChannelMap,
    SpectraCovarianceWarning,
    SpectraRecoveryError,
    SpectraRecoveryResult,
    bundle_to_emtf,
    edi_to_emtf,
    emtf_to_bundle,
    recover_spectra_transfer_functions,
    resolve_spectra_channels,
    spectra_to_emtf,
    emtf_to_edi,
    write_edi,
)
from .datatypes import (
    DataTypeDefinition,
    get_emtf_datatype,
    list_emtf_datatypes,
    register_emtf_datatype,
)
from .document import EMTF
from .estimates import StatisticalEstimate
from .orientation import (
    ApproximateVarianceRotationWarning,
    DerivedDataRotationWarning,
    EMTFRotationError,
    EMTFRotationWarning,
    LegacyRotationAssumptionWarning,
    RotationMatrices,
    UnsupportedEstimateRotationWarning,
    horizontal_inverse_rotation_matrix,
    horizontal_rotation_matrix,
    rotate_covariance,
    rotate_emtf,
    rotate_transfer_function,
)
from .transfer import TransferFunction
from .xml import (
    EMTFXMLParseError,
    EMTFXMLReader,
    EMTFXMLSerializationError,
    EMTFXMLSerializer,
    EMTFXMLWarning,
    EMTFXMLWriteWarning,
    EMTFXMLWriter,
    read_emtf_xml,
    write_emtf_xml,
)

__all__ = [
    "EMTF",
    "EMTFRotationError",
    "EMTFRotationWarning",
    "ApproximateVarianceRotationWarning",
    "UnsupportedEstimateRotationWarning",
    "DerivedDataRotationWarning",
    "LegacyRotationAssumptionWarning",
    "RotationMatrices",
    "horizontal_rotation_matrix",
    "horizontal_inverse_rotation_matrix",
    "rotate_covariance",
    "rotate_transfer_function",
    "rotate_emtf",
    "DataLossWarning",
    "EMTFEDIConversionError",
    "SpectraCovarianceWarning",
    "SpectraRecoveryError",
    "SpectraChannelMap",
    "SpectraRecoveryResult",
    "resolve_spectra_channels",
    "recover_spectra_transfer_functions",
    "spectra_to_emtf",
    "edi_to_emtf",
    "emtf_to_edi",
    "write_edi",
    "bundle_to_emtf",
    "emtf_to_bundle",
    "TransferFunction",
    "StatisticalEstimate",
    "DataTypeDefinition",
    "register_emtf_datatype",
    "get_emtf_datatype",
    "list_emtf_datatypes",
    "EMTFXMLReader",
    "EMTFXMLParseError",
    "EMTFXMLWarning",
    "read_emtf_xml",
    "EMTFXMLSerializer",
    "EMTFXMLSerializationError",
    "EMTFXMLWriteWarning",
    "EMTFXMLWriter",
    "write_emtf_xml",
]
