#!/usr/bin/env python
"""
Code benchmark case 045
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""

from __future__ import annotations

import os

import matplotlib.pyplot as plt

os.makedirs(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_045\\outputs",
    exist_ok=True,
)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites

sites = ensure_sites(
    "D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset",
    verbose=0,
)
print(f"Loaded {len(list(sites))} stations")

sites_corr = sites  # no static-shift correction

# Depth-of-investigation and sensitivity analysis
from pycsamt.emtools.csumt import (
    depth_coverage_table,
    plot_depth_section,
)

doi_table = depth_coverage_table(sites_corr)
doi_table.to_csv(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_045\\outputs"
    + "/depth_of_investigation.csv",
    index=False,
)
ax_doi = plot_depth_section(sites_corr)
ax_doi.get_figure().savefig(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_045\\outputs"
    + "/depth_of_investigation.png",
    dpi=150,
    bbox_inches="tight",
)
print("Depth-of-investigation and sensitivity outputs written.")

plt.show()
print("Workflow complete.")
