#!/usr/bin/env python
"""
Code benchmark case 005
Generated by pycsamt CodeGenerationAgent — 2026-07-13
This script reproduces the processing workflow automatically.
"""

from __future__ import annotations

import os

import matplotlib.pyplot as plt

os.makedirs(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_005\\outputs",
    exist_ok=True,
)

# ── load MT data ──────────────────────────────────────────────
from pycsamt.emtools._core import ensure_sites

sites = ensure_sites(
    "D:\\projects\\pycsamt\\paper_repro\\field\\l26plt\\three_station_replay_subset",
    verbose=0,
)
print(f"Loaded {len(list(sites))} stations")

# ── quality control ───────────────────────────────────────────
from pycsamt.emtools.qc import (
    build_qc_table,
    plot_frequency_confidence_psection,
    qc_flags,
)

qc_table = build_qc_table(sites)
flags = qc_flags(sites, min_frac_ok=0.6, min_snr_med=2.0)
fig_qc = plot_frequency_confidence_psection(sites).get_figure()
fig_qc.savefig(
    "D:\\projects\\pycsamt\\paper_repro\\code_replay\\v2.0.0\\generated_scripts\\case_005\\outputs"
    + "/qc_confidence.png",
    dpi=150,
    bbox_inches="tight",
)

sites_corr = sites  # no static-shift correction

plt.show()
print("Workflow complete.")
